---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(corrplot)
library(MASS)
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
 
```{r cars}
red <- data.frame(read.csv("https://raw.githubusercontent.com/jjohn81/DATA621_Final_Project/master/winequality-red.csv", sep = ";"))
white <- data.frame(read.csv("https://raw.githubusercontent.com/jjohn81/DATA621_Final_Project/master/winequality-white.csv", sep = ";"))

#checking that column names are the same
names(red)
names(white)
```

## Summary


```{r pressure, echo=FALSE}
summary(red)

#quality of whites from 3 to 9 (mean = 5.878)
summary(white)

```
White wines  total.sulfur.dioxide and free.sulfur.dioxide contents are alot higher than white wines
Red  wine has more  fixed.acidity   volatile.acidity and  more chlorides



```{r pressure, echo=FALSE}
plot(red$quality)

#quality of whites from 3 to 9 (mean = 5.878)
plot(white$quality)

```


```{r}
red$type <- as.factor("R")
white$type <- as.factor("W")
wines <- rbind(red,white)

# 6497 obs. of  13 variables
str(wines)


# Data Visualizations (to fill in) - boxplots, etc. 

# Scatterplot matrix

panel.cor <- function(x, y, digits=2, prefix="", cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  txt <- paste(prefix, txt, sep="")
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = cex.cor * r)
}

pairs(~quality + fixed.acidity + volatile.acidity + citric.acid + residual.sugar + 
        chlorides + free.sulfur.dioxide + total.sulfur.dioxide + density +pH + 
        sulphates + alcohol + type, data = wines,
      lower.panel=panel.smooth, upper.panel=panel.cor, pch=20, main="Wines Scatterplot Matrix")
```

```{r}
corrplot(cor(red[1:12]))
corrplot(cor(white[1:12]))
```

#### Research Question


```{r}
white <- white[,1:12]
white$quality <- as.factor(white$quality )

```




```{r}

set.seed(100)
trainingRows <- sample(1:nrow(white), 0.7 * nrow(white))
trainingData <- white[trainingRows, ]
testData <- white[-trainingRows, ]

```

```{r}
fullModel <- polr(quality ~. , data = trainingData, Hess=TRUE)
summary(fullModel)

```

```{r}
p <- predict(fullModel, testData)
confusionMatrix(p, testData$quality)
```

```{r}
stepModel <- step(m)

```
```{r}
p <- predict(stepModel, testData)
confusionMatrix(p, testData$quality)
```

 